name: Continuous Delivery

on:
  push:
    branches: ["main"]

env:
    IMAGE_NAME: applifecycle
    AZURE_WEBAPP_NAME_STG: AppLifecycle-stg
    AZURE_WEBAPP_NAME_PRD: AppLifecycle
jobs:
    build:
          runs-on: ubuntu-latest
          steps:
              - uses: actions/checkout@v4

              - name: Setup Java SDK
                uses: actions/setup-java@v4
                with:
                  distribution: 'temurin' 
                  java-version: '21'

              - name: Login to DockerHub
                uses: docker/login-action@v3
                with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

              - name: Build and Push container to DockerHub
                uses: docker/build-push-action@v6
                with:
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
    deploy-stg:
        runs-on: ubuntu-latest
        needs: build
        environment: stg
        steps:
          - name: Deploy to Azure Web App
            id: deploy-to-webapp-stg
            uses: azure/webapps-deploy@v2
            with:
              app-name: ${{ env.AZURE_WEBAPP_NAME_STG }}
              publish-profile: ${{ secrets.AZURE_PROFILE_STG }}
              images: '${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest'
    deploy-prs:
        runs-on: ubuntu-latest
        needs: deploy-stg
        environment: prd
        steps:
          - name: Deploy to Azure Web App
            id: deploy-to-webapp-prd
            uses: azure/webapps-deploy@v2
            with:
              app-name: ${{ env.AZURE_WEBAPP_NAME_PRD }}
              publish-profile: ${{ secrets.AZURE_PROFILE_PRD }}
              images: '${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest'
